# Copyright (c) 2018, GoodData Corporation. All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

require 'rubygems'

require 'bundler/setup'
require 'bundler/gem_tasks'

require 'rake/testtask'
require 'rake/notes/rake_task'
require 'rspec/core/rake_task'

# require 'yard'

desc 'Run Rubocop'
task :cop do
  exec 'rubocop -a -c .rubocop.yml lib/ spec/'
end

RSpec::Core::RakeTask.new(:test)

namespace :test do
  desc 'Run unit tests'
  RSpec::Core::RakeTask.new(:unit) do |t|
    t.pattern = 'spec/unit/**/*.rb'
  end

  desc 'Run integration tests'
  RSpec::Core::RakeTask.new(:integration) do |t|
    t.pattern = 'spec/integration/**/*.rb'
  end

  desc 'Run coding style tests'
  RSpec::Core::RakeTask.new(:cop) do
    Rake::Task['cop'].invoke
  end

  task all: [:unit, :integration, :cop]
end

desc 'Run all tests'
task test: 'test:all'

task :usage do
  puts 'No rake task specified, use rake -T to list them'
end
